[build]
compiler = "gcc"

[[targets]]
name = "noop"
src = "./src/"
include_dir = "./include"
type = "exe"
cflags = "-Wall -Werror"
libs = ""

[[targets]]
name = "arena"
src = "./src/"
include_dir = "./include"
type = "dll"
cflags = "-Wall -Werror"
libs = ""

